##---
# Source: prometheus/templates/node-exporter-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.4.3
    component: "node-exporter"
    heritage: Tiller
    release: prod
  name: prod-prometheus-node-exporter
  namespace: monitoring
