---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chartGitPath: grafana
  releaseName: grafana

  values:
    server:
      image: "grafana/grafana:5.1.1"

      ingress:
        enabled: true
        hosts:
          - grafana.prod

      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 100Mi
      
      setDatasource:
        enabled: true
        image: appropriate/curl:latest
        datasource:
          name: default
          type: prometheus
          url: https://prometheus.prod
          