apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  minReadySeconds: 5
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
      