apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  minReadySeconds: 5
  replicas: 4
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.12-perl
        ports:
        - containerPort: 80
      
