##---
# Source: prometheus/templates/server-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.4.3
    component: "server"
    heritage: Tiller
    release: prod
  name: prod-prometheus-server
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: prod-prometheus-server
    namespace: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prod-prometheus-server
