---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flux-helm-operator
  labels:
    name: flux-helm-operator
    app: weave-flux
    weave-cloud-component: flux
    weave-flux-component: helm-operator
  namespace: weave
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-helm-operator
        app: weave-flux
        weave-cloud-component: flux
        weave-flux-component: helm-operator
    spec:
      volumes:
      - name: git-key
        secret:
          secretName: flux-git-deploy
      serviceAccountName: flux
      containers:
      - name: flux-helm-operator
        image: {{ .Values.fluxHelm.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: git-key
          mountPath: /etc/fluxd/ssh
        args:
        - --git-url={{ .Values.fluxHelm.gitUrl }}
        - --git-branch={{ .Values.fluxHelm.gitBranch }}
        - --git-charts-path={{ .Values.fluxHelm.gitChartsPath }}