#
# Values for flux and flux-helm operators
#
flux:
  # Docker Image for flux
  image: quay.io/weaveworks/flux:1.3.0
  
  # Command line args 
  gitUrl: git@github.com:evnsio/flux-playground
  gitPath: environments/production
  gitBranch: master
  gitPollInterval: 60s

fluxHelm:
  # Docker Image for flux-helm
  image: quay.io/weaveworks/helm-operator:0.1.0-alpha

  # Command line args 
  gitUrl: git@github.com:evnsio/flux-playground.git
  gitBranch: master
  gitChartsPath: charts
