##---
# Source: prometheus/templates/kube-state-metrics-serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    chart: prometheus-5.4.3
    component: "kube-state-metrics"
    heritage: Tiller
    release: prod
  name: prod-prometheus-kube-state-metrics
  namespace: monitoring
